---
galaxy_info:
  author: Patrick BONNEFOI
  role_name: traefik
  namespace: pbonnefoi
  description: Install Traefik
  company: none
  license: MLP2
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bullseye
  galaxy_tags:
    - virtualization
dependencies: []